"""rename department

Revision ID: 36f97dd05ab9
Revises: e2af8ce39abe
Create Date: 2024-10-03 17:57:50.892028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f97dd05ab9'
down_revision = 'e2af8ce39abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
